'use client';
import {useEffect,useState} from 'react';
import type {Group} from '@/lib/types';
async function access(body:unknown){const r=await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);return d}
export function AccessGate({onSave}:{onSave:()=>Promise<void>}){const [message,setMessage]=useState(''),[busy,setBusy]=useState(false); useEffect(()=>{const open=()=>{const params=new URLSearchParams(location.hash.slice(1));const token=params.get('group');if(token){history.replaceState(null,'',location.pathname);setBusy(true);access({type:'group',token}).then(onSave).catch(e=>setMessage(e.message)).finally(()=>setBusy(false))}};open();window.addEventListener('hashchange',open);return()=>window.removeEventListener('hashchange',open)},[onSave]);
return busy||message?<p role="status" className="notice">{message||'Opening your group…'}</p>:null}
export function AccessPanel({onSave}:{onSave:()=>Promise<void>}){const [message,setMessage]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);

 return <section className="panel"><h2>Your group’s workspace</h2><p>Open the private group link supplied by your instructor. No student account is needed. Keep that link within your group.</p>{busy&&<p>Opening your group…</p>}<details><summary>Instructor access</summary><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await access({type:'instructor',password});setPassword('');await onSave()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}><label>Instructor password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>Open instructor workspace</button></form></details><p role="status">{message}</p></section>
}
export function GroupLinks(){const [groups,setGroups]=useState<{id:string;name:string;token:string}[]>([]),[name,setName]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);async function load(){const r=await fetch('/api/access');const d=await r.json();if(!r.ok)throw new Error(d.error);setGroups(d.groups)}useEffect(()=>{load().catch(e=>setMessage(e.message))},[]);return <section className="panel"><h2>Group links</h2><p>Create one gallery entry for each existing group. Send each link only to that group. Everyone with the link can edit its work. Use Reveal gallery when everyone has posted.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await access({type:'create',name});setName('');await load();setMessage('Group created. Copy its link below.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}><label>Group name<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="Group 1"/></label><button className="primary" disabled={busy}>Create group link</button></form><p role="status">{message}</p>{groups.map(g=><div className="detail" key={g.id}><h4>{g.name}</h4><input aria-label={g.name+' private link'} readOnly value={location.origin+'/#group='+g.token} onFocus={e=>e.target.select()}/><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/#group='+g.token);setMessage(g.name+' link copied.')}catch{setMessage('Select and copy the link above.')}}}>Copy link</button></div>)}<p className="small">Members should coordinate edits. The most recently saved design replaces the previous one.</p></section>}
export function Screenshots({group,editable,onSave}:{group:Group;editable:boolean;onSave:()=>Promise<void>}){const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);return <section className="screenshots"><h4>Workflow screenshots</h4><div className="screenshot-grid">{(group.screenshots||[]).map(id=><div key={id}><a href={'/api/screenshots?id='+id} target="_blank" rel="noopener noreferrer"><img src={'/api/screenshots?id='+id} alt={group.name+' workflow screenshot'}/></a>{editable&&<button className="textbutton" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/screenshots?id='+id,{method:'DELETE'});if(!r.ok)throw new Error((await r.json()).error);await onSave()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>Remove screenshot</button>}</div>)}</div>{editable&&<label>Add a screenshot (up to three, 5 MB each)<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy||(group.screenshots||[]).length>=3} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024){setMessage('Choose an image smaller than 5 MB.');return}setBusy(true);try{const r=await fetch('/api/screenshots',{method:'POST',headers:{'Content-Type':f.type},body:f});if(!r.ok)throw new Error((await r.json()).error);setMessage('Screenshot saved.');await onSave()}catch(e){setMessage((e as Error).message)}finally{setBusy(false);e.target.value=''}}}/></label>}{!editable&&!group.screenshots?.length&&<p className="small">No screenshot submitted.</p>}<p role="status">{busy?'Saving…':message}</p></section>}
