import {randomUUID} from 'node:crypto';
import sharp from 'sharp';
import {sameOrigin,user} from '@/lib/access';
import {sqlite} from '@/lib/lab-store';
export const dynamic='force-dynamic';
const error=(message:string,status:number)=>Response.json({error:message},{status});
export async function GET(req:Request){const u=await user();if(!u)return error('Group access required.',401);const id=new URL(req.url).searchParams.get('id');const row=sqlite().prepare('SELECT group_id,image FROM screenshots WHERE id=?').get(id||'') as {group_id:string;image:Uint8Array}|undefined;if(!row)return error('Image not found.',404);const phase=sqlite().prepare('SELECT revealed AS phase FROM gallery_settings WHERE id=1').get() as {phase:number}|undefined;if(u.userId!=='instructor'&&u.userId!==row.group_id&&phase?.phase!==1)return error('Image unavailable.',403);return new Response(new Uint8Array(row.image),{headers:{'Content-Type':'image/png','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}})}
export async function POST(req:Request){if(!sameOrigin(req))return error('Please use this site.',403);const u=await user();if(!u||u.userId==='instructor')return error('Open a group link first.',403);const phase=()=>Number(sqlite().prepare('SELECT revealed AS phase FROM gallery_settings WHERE id=1').get()?.phase||0);if(phase()!==0)return error('The gallery is revealed and edits are closed.',409);const reader=req.body?.getReader();if(!reader)return error('Select an image.',400);const chunks:Uint8Array[]=[];let size=0;while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>5*1024*1024){await reader.cancel();return error('Choose an image smaller than 5 MB.',413)}chunks.push(r.value)}let image:Buffer;try{const input=Buffer.concat(chunks);const decoder=sharp(input,{limitInputPixels:25000000});const meta=await decoder.metadata();if(!['png','jpeg','webp'].includes(meta.format||''))return error('Use PNG, JPEG, or WebP.',400);image=await decoder.rotate().resize({width:2400,height:2400,fit:'inside',withoutEnlargement:true}).png().toBuffer()}catch{return error('This image could not be read.',400)}
 const id=randomUUID();const result=sqlite().prepare('INSERT INTO screenshots(id,group_id,image,created) SELECT ?,?,?,? WHERE COALESCE((SELECT revealed AS phase FROM gallery_settings WHERE id=1),0)=0 AND (SELECT COUNT(*) FROM screenshots WHERE group_id=?)<3').run(id,u.userId,image,new Date().toISOString(),u.userId);if(!result.changes)return error('Maximum three screenshots, or the round has closed.',409);return Response.json({id})}
export async function DELETE(req:Request){if(!sameOrigin(req))return error('Please use this site.',403);const u=await user();if(!u)return error('Group access required.',401);const id=new URL(req.url).searchParams.get('id');const r=sqlite().prepare('DELETE FROM screenshots WHERE id=? AND group_id=? AND COALESCE((SELECT revealed AS phase FROM gallery_settings WHERE id=1),0)=0').run(id||'',u.userId);return r.changes?Response.json({ok:true}):error('Screenshot unavailable or frozen.',409)}
