import {z} from 'zod';
import {user,sameOrigin} from '@/lib/access';
import {sqlite} from '@/lib/lab-store';
export const dynamic='force-dynamic';
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}});
const text=(max:number)=>z.string().trim().min(1).max(max);
const action=z.enum(['ANSWER','CLARIFY','ESCALATE']);
const schema=z.object({tool:text(120),explanation:text(1800),link:z.string().trim().max(1000).refine(v=>!v||/^https?:\/\//i.test(v),'Use an http or https link.'),action1:action,output1:text(16000),action2:action,output2:text(16000)});
export async function GET(){try{const u=await user();const revealed=!!sqlite().prepare('SELECT revealed FROM gallery_settings WHERE id=1').get()?.revealed;const instructor=u?.userId==='instructor';if(!u)return json({signedIn:false,instructor:false,revealed,mine:null,groups:[]});const groups=sqlite().prepare(instructor||revealed?'SELECT id,name FROM lab_groups ORDER BY name':'SELECT id,name FROM lab_groups WHERE id=?').all(...(instructor||revealed?[]:[u.userId])).map(g=>({id:String(g.id),name:String(g.name),reflection:sqlite().prepare('SELECT reflection FROM gallery_reflections WHERE group_id=?').get(String(g.id))?.reflection||'',entry:sqlite().prepare('SELECT * FROM gallery_entries WHERE group_id=?').get(String(g.id))||null,screenshots:sqlite().prepare('SELECT id FROM screenshots WHERE group_id=? ORDER BY created').all(String(g.id)).map(s=>s.id)}));return json({signedIn:true,instructor,revealed,mine:groups.find(g=>g.id===u.userId)||null,groups:instructor||revealed?groups:[]})}catch{return json({error:'Could not load the gallery. Please try again.'},503)}}
export async function POST(req:Request){try{if(!sameOrigin(req))return json({error:'Please post from this site.'},403);const u=await user();if(!u)return json({error:'Open your group link first.'},401);const raw=await req.text();if(raw.length>40000)return json({error:'This post is too long.'},413);let p;try{p=JSON.parse(raw)}catch{return json({error:'Invalid post.'},400)}if(p.type==='reveal'){if(u.userId!=='instructor')return json({error:'Instructor access required.'},403);sqlite().prepare('INSERT INTO gallery_settings(id,revealed) VALUES(1,1) ON CONFLICT(id) DO UPDATE SET revealed=1').run();return json({ok:true})}if(u.userId==='instructor')return json({error:'Use a group link to post.'},403);if(p.type==='reflection'){const reflection=text(2000).safeParse(p.reflection);if(!reflection.success)return json({error:'Write a reflection of up to 2,000 characters.'},400);const changed=sqlite().prepare('INSERT INTO gallery_reflections(group_id,reflection,updated) SELECT ?,?,? WHERE COALESCE((SELECT revealed FROM gallery_settings WHERE id=1),0)=1 AND EXISTS(SELECT 1 FROM gallery_entries WHERE group_id=?) ON CONFLICT(group_id) DO UPDATE SET reflection=excluded.reflection,updated=excluded.updated').run(u.userId,reflection.data,new Date().toISOString(),u.userId);return changed.changes?json({ok:true}):json({error:'Post both challenge responses first. Reflections open after the reveal.'},409)}const result=schema.safeParse(p);if(!result.success)return json({error:result.error.issues[0].message},400);const v=result.data;const r=sqlite().prepare(`INSERT INTO gallery_entries(group_id,tool,explanation,link,action1,output1,action2,output2,updated) SELECT ?,?,?,?,?,?,?,?,? WHERE COALESCE((SELECT revealed FROM gallery_settings WHERE id=1),0)=0 AND EXISTS(SELECT 1 FROM screenshots WHERE group_id=?) ON CONFLICT(group_id) DO UPDATE SET tool=excluded.tool,explanation=excluded.explanation,link=excluded.link,action1=excluded.action1,output1=excluded.output1,action2=excluded.action2,output2=excluded.output2,updated=excluded.updated`).run(u.userId,v.tool,v.explanation,v.link,v.action1,v.output1,v.action2,v.output2,new Date().toISOString(),u.userId);if(!r.changes)return json({error:'Add a workflow screenshot first. If the gallery has been revealed, edits are closed.'},409);return json({ok:true})}catch{return json({error:'Your post was not saved. Keep your text and try again.'},503)}}
